### ISSUE TITLE
Found deleted items when iterating the map

### ISSUE THREAD

**Issue by zhangyunhao116** [cockroachdb/swiss#33]
```
package gomapbench

import (
	"math/rand"
	"testing"

	"github.com/cockroachdb/swiss"
)

func TestRangeStoreAndDelete(t *testing.T) {
	const maxItemInBucket = 7
	// Range random delete.
	const count = maxItemInBucket * 4
	m := swiss.New[int, int](count)
	rangefound := [count * 2]int{}
	rangedeleted := [count * 2]int{}
	randints := [count]int{}
	for i := range randints {
		r := rand.Int()
		for r == 0 || r == 1 {
			// 0 is the default value.
			// 1 used to trigger grow.
			r = rand.Int()
		}
		randints[i] = r
		m.Put(r, r)
	}

	var (
		foundlen int
		isgrow   bool
	)
	m.All(func(k, _ int) bool {
		if !isgrow {
			isgrow = true
			m.Put(1, 1)
		}
		rangefound[foundlen] = k
		r := randints[rand.Intn(count)]
		m.Delete(r)
		rangedeleted[foundlen] = r
		foundlen++
		return true
	})

	// Can't range deleted items.
	for i := 0; i < foundlen; i++ {
		deleted := rangedeleted[i]
		afterdeleted := rangefound[i+1 : foundlen]
		for j := 0; j < len(afterdeleted); j++ {
			if afterdeleted[j] == deleted {
				t.Fatal("found deleted", deleted)
			}
		}
	}
}

```

**Comment by petermattis** [comment]
```
// All calls yield sequentially for each key and value present in the map. If
// yield returns false, range stops the iteration. The map can be mutated
// during iteration, though there is no guarantee that the mutations will be
// visible to the iteration.
```

Note the last sentence in the godoc comment for `All`. There is no guarantee that a mutation performed during the iteration will be visible to the iteration. This is similar to the behavior of Go's builtin map. There is a strong implementation reason for this behavior and changing it is not feasible.

**Comment by thepudds** [comment]
Hi @petermattis , FWIW, I think the behavior implemented & documented here is a bit different than the current builtin Go runtime map. From the [Go spec](https://go.dev/ref/spec#For_statements):

> If a map entry that has not yet been reached is removed during iteration, the corresponding iteration value will not be produced.

The README here says "[...] and iteration stability akin to Go's builtin map if the map is mutated during iteration", which I initially took to mean the intent was identical iteration semantics as the Go runtime map.

Shortly after you first published your map, I had looked at fixing this in this implementation, and at the time, it seemed plausible (but maybe I was wrong at the time, or maybe I'm misremembering now 😅). 

I'll dig up my WIP change (at least to satisfy my curiosity of what I thought at the time), and I'll comment back here in a bit.
