### ISSUE TITLE
Question: Does swissmap shrink on key deletion?

### ISSUE THREAD

**Issue by Jakobovski** [cockroachdb/swiss#38]
Does swissmap suffer from the same key-deletion issue as golang map? Namely memory is not freed upon deleting of keys?

See https://github.com/golang/go/issues/20135

**Comment by petermattis** [comment]
`swiss.Map` has similar delete behavior to Go's builtin `map`. The Map grows during insertion, but does not shrink during deletion. However, deleted pointer values can be Gc'd. So can the memory associated with string keys.
